import {
    ThumbsUp,
    MessageSquare,
    FileText,
    Mail,
    CheckSquare,
    Circle,
    CheckSquare2,
    Star,
    Stars,
    PieChart,
    TextQuote,
    Slack,
    Webhook,
    MessageCircleReply,
    Sheet,
} from 'lucide-vue-next';
import { QuestionType, type Integration } from '~/types/survey';

// Zap,
// Laptop,
// Trello,
// Palette,
// DiamondPlus,

export const questionTypes = [
    {
        id: QuestionType.REACTION,
        label: 'Reaction',
        icon: ThumbsUp,
        description: 'Simple reaction feedback',
    },
    {
        id: QuestionType.SHORT_TEXT,
        label: 'Short text answer',
        icon: MessageSquare,
        description: 'Brief text response',
    },
    {
        id: QuestionType.LONG_TEXT,
        label: 'Long text answer',
        icon: FileText,
        description: 'Detailed text response',
    },
    {
        id: QuestionType.EMAIL,
        label: 'Email',
        icon: Mail,
        description: 'Collect email addresses',
    },
    {
        id: QuestionType.YES_NO,
        label: 'Yes / No',
        icon: CheckSquare,
        description: 'Binary choice question',
    },
    {
        id: QuestionType.RADIO,
        label: 'Radio options',
        icon: Circle,
        description: 'Single choice from multiple options',
    },
    {
        id: QuestionType.CHECKBOX,
        label: 'Checkbox options',
        icon: CheckSquare2,
        description: 'Multiple choice selection',
    },
    {
        id: QuestionType.RATING_5,
        label: '1 - 5 Rating scale',
        icon: Star,
        description: 'Five-point rating scale',
    },
    {
        id: QuestionType.RATING_7,
        label: '1 - 7 Rating scale',
        icon: Stars,
        description: 'Seven-point rating scale',
    },
    {
        id: QuestionType.NPS,
        label: 'Net Promoter Score',
        icon: PieChart,
        description: 'Measure customer loyalty (0-10)',
    },
    {
        id: QuestionType.STATEMENT,
        label: 'Statement',
        icon: TextQuote,
        description: 'Display text without requiring response',
    },
];

export const integrations = ref<Integration[]>([
    {
        id: 'slack',
        name: 'Slack',
        icon: Slack,
        badge: 'BUSINESS',
        enabled: false,
        iconColor: '#E01E5A',
    },
    // {
    //     id: 'teams',
    //     name: 'Microsoft Teams',
    //     icon: Laptop,
    //     badge: 'BUSINESS',
    //     enabled: false,
    //     iconColor: '#6264A7',
    // },
    {
        id: 'webhooks',
        name: 'Webhooks',
        icon: Webhook,
        badge: 'SCALE',
        enabled: false,
        iconColor: '#2E2E2E',
    },
    {
        id: 'email',
        name: 'Email',
        icon: Mail,
        enabled: false,
        iconColor: '#4A5568',
    },
    {
        id: 'responses-api',
        name: 'Responses API',
        icon: MessageCircleReply,
        badge: 'SCALE',
        enabled: false,
        external: true,
        iconColor: '#4A5568',
    },
    // {
    //     id: 'zapier',
    //     name: 'Zapier',
    //     icon: Zap,
    //     badge: 'BUSINESS',
    //     enabled: false,
    //     iconColor: '#FF4A00',
    // },
    {
        id: 'excel',
        name: 'Excel',
        icon: Sheet,
        enabled: false,
        external: true,
        isNested: true,
        iconColor: '#217346',
    },
    // {
    //     id: 'trello',
    //     name: 'Trello',
    //     icon: Trello,
    //     enabled: false,
    //     external: true,
    //     isNested: true,
    //     iconColor: '#0079BF',
    // },
    // {
    //     id: 'miro',
    //     name: 'Miro',
    //     icon: Palette,
    //     enabled: false,
    //     external: true,
    //     isNested: true,
    //     iconColor: '#FFD02F',
    // },
    // {
    //     id: 'create-zap',
    //     name: 'Create Zap',
    //     icon: DiamondPlus,
    //     enabled: false,
    //     external: true,
    //     isNested: true,
    //     iconColor: '#FF4A00',
    // },
]);
